language: android
before_install:
- nvm install 8
- node --version
install:
- npm install
android:
  components:
  - build-tools-30.0.2
  - android-30
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script:
- npm run ci
- cd android && ./gradlew clean
