matrix:
  include:
    - language: node_js
      node_js:
        - "12"
      script: 
        - chmod +x .travis/ci_node.sh 
        - .travis/ci_node.sh

    - os: osx
      language: objective-c
      osx_image: xcode9.4
      env:
        - JOB_NAME=IOS
      script: 
        - chmod +x .travis/ci.sh
        - .travis/ci.sh

    - os: linux
      language: android
      jdk: oraclejdk8
      sudo: required
      android:
        components:
          - platform-tools
          - tools
          - build-tools-30.0.2
          - android-30
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-google_play_services
      env:
        - JOB_NAME=ANDROID
      script:
        - chmod +x .travis/ci.sh
        - .travis/ci.sh
